source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '11.0'

workspace 'Hornet.xcworkspace'

def basePods()
  pod 'Hornet', :path => '../'
end

def ui_layer_pods
  pod 'SnapKit', '5.0.1'
#  pod 'RxCocoa', '6.2.0'
#  pod 'RxSwift', '6.2.0'
end

target 'Hornet_Example' do
  basePods
  
  target 'Home' do
    project 'Modules/Home/Home.xcodeproj'
    basePods
    ui_layer_pods
  end
end
